spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studyDemo
    username: demo
    password: Demo@123456

    #配置SQL监控
    filters: stat,wall,log4j